fix to check that an end time is not later than the start time
FlaskCon/traveller pull request #56
Opened 2021-09-10 10:38 UTC by kunmi02

This fix is to check the the end date or the end time is not later than the end date or the end time while creating schedules, activity and talks

2021-09-10 13:23 UTC, ThiefMaster commented on traveller/modules/schedule/view.py
> +        return True
That function makes the code less readable. Just put the check in the places where you call it atm...

2021-09-10 13:23 UTC, ThiefMaster commented on traveller/modules/schedule/view.py
> +# import datetime
committing commented-out code is usually not a good idea

2021-09-10 13:28 UTC, kunmi02 commented
@ThiefMaster Kindly review again

2021-09-10 13:37 UTC, Abdur-rahmaanJ commented
@kunmi02 ill do it by tonight

2021-09-10 14:15 UTC, jugmac00 requested changes

2021-09-10 14:15 UTC, jugmac00 commented on traveller/modules/schedule/view.py
> -        form.validate()
I do not think you can just delete `form.validiate` as there is more data than just the start and the end time.

2021-09-11 17:24 UTC, jugmac00 requested changes
There are a couple of bugs in your PR.

If you do not write automatic tests, at least you should test your code manually, ie create an instance and try your changes!

Thank you!

2021-09-11 17:24 UTC, jugmac00 commented on traveller/modules/schedule/view.py
> +        return True
Please remove unused code.

2021-09-11 17:24 UTC, jugmac00 commented on traveller/modules/schedule/view.py
> +        return mhelp.redirect_url('y.schedule', year=year)
This needs to be the other way round.

`if date.today() > form.date.data: `

2021-09-11 17:24 UTC, jugmac00 commented on traveller/modules/schedule/view.py
> +            return mhelp.redirect_url('y.schedule', year=year)
It is the other way round.

2021-09-11 17:24 UTC, jugmac00 commented on traveller/modules/schedule/view.py
> +            return mhelp.redirect_url('y.schedule', year=year)
It is the other way round.

2021-09-11 17:24 UTC, jugmac00 commented on traveller/modules/schedule/view.py
> +            return mhelp.redirect_url('y.schedule', year=year)
It is the other way round.

2021-09-11 17:24 UTC, jugmac00 commented on traveller/modules/schedule/view.py
> +            return mhelp.redirect_url('y.schedule', year=year)
It is the other way round.

2021-09-12 09:28 UTC, kunmi02 commented
@jugmac00 Thanks for the review and suggested changes. I have applied the changes and also tested them. Kindly review it.

2021-09-15 12:55 UTC, jugmac00 requested changes
Please delete the unused function `_date_difference`, then we are good to go.

2021-09-15 12:55 UTC, jugmac00 commented on traveller/modules/schedule/view.py
> +        return True
This unused function is still not deleted.

2021-09-15 14:12 UTC, kunmi02 commented
@jugmac00 The unused function has been removed.
Thanks for your time and patience.

Kindly review again, please

2021-09-15 17:32 UTC, jugmac00 approved these changes

2021-09-15 17:33 UTC, merged